### ISSUE TITLE
NoSuchMethodError thrown when calling compile

### ISSUE THREAD

**Issue by linde9821** [ZacSweers/kotlin-compile-testing#307]
When running `compile` I get the following exception:

```
'org.jetbrains.kotlin.cli.common.ExitCode org.jetbrains.kotlin.cli.common.CLICompiler.exec(org.jetbrains.kotlin.cli.common.messages.MessageCollector, org.jetbrains.kotlin.config.Services, org.jetbrains.kotlin.cli.common.arguments.CommonCompilerArguments)'
java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.cli.common.ExitCode org.jetbrains.kotlin.cli.common.CLICompiler.exec(org.jetbrains.kotlin.cli.common.messages.MessageCollector, org.jetbrains.kotlin.config.Services, org.jetbrains.kotlin.cli.common.arguments.CommonCompilerArguments)'
	at com.tschuchort.compiletesting.AbstractKotlinCompilation.compileKotlin(AbstractKotlinCompilation.kt:274)
	at com.tschuchort.compiletesting.KotlinCompilation.compileJvmKotlin(KotlinCompilation.kt:419)
	at com.tschuchort.compiletesting.KotlinCompilation.compile(KotlinCompilation.kt:606)
```

using version 0.0.7

My setup looks like this:

```kotlin
    @OptIn(ExperimentalCompilerApi::class)
    @Test
    fun `must create compileable code`() {
        val sut = HibernateCodeGeneratorImpl()

        val fileSpecResult = sut.generate()

        val sourceFile = SourceFile.kotlin("${fileSpecResult.name}.kt", fileSpecResult.toString())
        val compile = KotlinCompilation().apply {
            sources = listOf(sourceFile)

            inheritClassPath = true
            messageOutputStream = System.out
        }

        val compilationResult = compile.compile()

        assertThat(compilationResult.exitCode).isEqualTo(KotlinCompilation.ExitCode.OK)
    }

```

**Comment by ZacSweers** [comment]
Can you share a minimally reproducible sample project?

**Comment by proberts-gfm** [comment]
I ran into this issue when trying to use version 0.7.0 with kotlin 2.0.21. Downgrading to 0.6.0 seemed to fix it for me.

**Comment by ZacSweers** [comment]
Sorry but that's really not helpful, I'll need a reproducer project to do anything here

**Comment by proberts-gfm** [comment]
Sorry if I was unclear - my previous comment was just to try to help people that stumble on this in the future. You will get that NoSuchMethodError if you are trying to use 0.7.0 with Kotlin 2.0.x, as you should be using 0.6.0.
