### ISSUE TITLE
0.6.0+ : java.lang.NullPointerException: getService(...) must not be null

### ISSUE THREAD

**Issue by tokazio** [ZacSweers/kotlin-compile-testing#308]
Upgrading to:
kotlin = 2.0.20
ksp = 2.0.21-1.0.27
this lib = 0.6.0

I've got an exception:
```
java.lang.NullPointerException: getService(...) must not be null
	at ksp.org.jetbrains.kotlin.asJava.KotlinAsJavaSupport$Companion.getInstance(KotlinAsJavaSupport.kt:67)
	at ksp.org.jetbrains.kotlin.asJava.finder.JavaElementFinder.<init>(JavaElementFinder.kt:33)
	at ksp.org.jetbrains.kotlin.analysis.api.standalone.base.projectStructure.FirStandaloneServiceRegistrar.registerProjectModelServices(FirStandaloneServiceRegistrar.kt:45)
	at com.google.devtools.ksp.impl.KotlinSymbolProcessing.registerProjectServices(KotlinSymbolProcessing.kt:279)
	at com.google.devtools.ksp.impl.KotlinSymbolProcessing.createAASession(KotlinSymbolProcessing.kt:244)
	at com.google.devtools.ksp.impl.KotlinSymbolProcessing.execute(KotlinSymbolProcessing.kt:454)
	at com.tschuchort.compiletesting.Ksp2PrecursorTool.execute(Ksp2.kt:110)
	at com.tschuchort.compiletesting.AbstractKotlinCompilation.compileKotlin(AbstractKotlinCompilation.kt:210)
	at com.tschuchort.compiletesting.KotlinCompilation.compileJvmKotlin(KotlinCompilation.kt:419)
	at com.tschuchort.compiletesting.KotlinCompilation.compile(KotlinCompilation.kt:606)
```

When calling:
```
KotlinCompilation()
      .apply {
        sources = source.toList()
        workingDir = temporaryFolder
        inheritClassPath = true
        jvmTarget = JvmTarget.JVM_17.description
        configureKsp(useKsp2 = true) {
          symbolProcessorProviders.add(MySymbolProvider())
          incremental = true
          incrementalLog = true
          withCompilation = true
          loggingLevels = setOf(CompilerMessageSeverity.INFO)
        }
      }.compile()
```

**Comment by ZacSweers** [comment]
Can you share a minimally reproducible sample project?

**Comment by LucasIME** [comment]
Running into the same problem here after the upgrade. Only happens when trying to build through Intellij compiler. When running through Gradle things work just fine.

**Comment by ZacSweers** [comment]
What's the IntelliJ compiler?

**Comment by ZacSweers** [comment]
Closing due to lack of details

**Comment by ZacSweers** [comment]
I've never had success with the IntelliJ runner. Use the gradle test runner if your project is a gradle project
