### ISSUE TITLE
MainComponentRegistrar is not compatible with this version of compiler

### ISSUE THREAD

**Issue by galex** [ZacSweers/kotlin-compile-testing#310]
Hello,

Trying the latest `0.7.0` on with Kotlin `2.1.0`, this test fails:
```kotlin
class CopyIrPluginTest {

    @OptIn(ExperimentalCompilerApi::class)
    @Test
    fun `IR plugin success`() {
        val kotlinSource = SourceFile.kotlin(
            "KClass.kt", """
        class KClass {
            fun foo() {
                // Classes from the test environment are visible to the compiled sources
                println("Hello, world!") 
            }
        }
    """
        )

        val result = KotlinCompilation().apply {
            sources = listOf(kotlinSource)
            // pass your own instance of a compiler plugin
            compilerPluginRegistrars = listOf(CopyComponentRegistrar())
            commandLineProcessors = listOf(CopyCommandLineProcessor())
            inheritClassPath = true
            messageOutputStream = System.out // see diagnostics in real time
        }.compile()

        assertThat(result.exitCode).isEqualTo(ExitCode.OK)
    }
}
```
This is the error:
```
e: The provided plugin com.tschuchort.compiletesting.MainComponentRegistrar is not compatible with this version of compiler.
java.lang.AbstractMethodError: Receiver class com.tschuchort.compiletesting.MainComponentRegistrar does not define or inherit an implementation of the resolved method 'abstract void registerProjectComponents(com.intellij.mock.MockProject, org.jetbrains.kotlin.config.CompilerConfiguration)' of interface org.jetbrains.kotlin.compiler.plugin.ComponentRegistrar.
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.registerExtensionsFromPlugins$cli_base(KotlinCoreEnvironment.kt:755)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$ProjectEnvironment.registerExtensionsFromPlugins(KotlinCoreEnvironment.kt:194)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.configureProjectEnvironment(KotlinCoreEnvironment.kt:652)
	at org.jetbrains.kotlin.cli.jvm.compiler.pipeline.JvmCompilerPipelineKt.createProjectEnvironment(jvmCompilerPipeline.kt:287)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:139)
```
This is very weird, as I do see this function being implemented in the library's code:
```
internal class MainComponentRegistrar : ComponentRegistrar, CompilerPluginRegistrar() {

  // Legacy plugins
  override fun registerProjectComponents(project: MockProject, configuration: CompilerConfiguration) { ... }
```
If do not set `compilerPluginRegistrars` and/or `commandLineProcessors`, the test passes so it does seem related to how the custom compiler plugin is set.

Any help would be greatly appreciated 🙏

**Comment by galex** [comment]
Godamnit 🤦 

Using `org.jetbrains.kotlin:kotlin-compiler-embeddable`, the test works.
